#!/usr/bin/env bash

TEST_HOME="$( cd "$( dirname "$0" )" && pwd )"
PROJECT_HOME="$( cd $TEST_HOME/.. && pwd )"

$TEST_HOME/setup

NATIVES_CMD="$PROJECT_HOME/bin/natives list $($TEST_HOME/list_all)"
NATIVE_PACKAGES="$( $NATIVES_CMD )"
echo " * Native packages: $NATIVE_PACKAGES"

if [ -n "$NATIVE_PACKAGES" ]; then
  echo " * Installing native packages.."
  INSTALL_CMD="$TEST_HOME/vendored/pacapt -v -S"
  $INSTALL_CMD $NATIVE_PACKAGES
fi

echo " * Installing gems.."
bundle install --gemfile $TEST_HOME/data/Gemfile --path bundle --verbose

EXIT_CODE=$?
echo " * Exit code: $EXIT_CODE"
echo ""

if [ $EXIT_CODE -eq 0 ]; then
  echo "SUCCESS"
else
  echo "FAILED"
fi
